# 新浪应用 转化短接口API
api_url: https://api.weibo.com/2/short_url/shorten.json
# 新浪应用Token
acess_token: 2.00FMIcADLQuzWB8dcef1c8f7HxYv2E

# 生成二维码保存路径（注意操作系统）
DEST_PATH: D://qrCode/picture

spring:
  redis:
    database: 0
    host: 127.0.0.1
    pool: 6379
    password: Andy
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
    timeout: 3000

